### PR TITLE
Fix regression in unsubscribe link to allow passing of email type

### PR DESCRIPTION
**Pull request by phamann**
ronseal

/cc @debugwand

### CODE REVIEW

**Comment by debugwand** [comment]
looks good, however I am getting errors on the lambda function when called from unsub (will have nothing to do with this). Will take a look and fix if necessary.

**Comment by phamann** [comment]
I got an error on first try but worked after refresh.

**Comment by debugwand** [comment]
I am not sure how, because I am looking for the bit of the code that passes through the concept id to the unsubscribe lambda and I don't think it is present.

**Comment by laurieboyes** [comment]
Cool 👍

**Pull request merged**
