### PR TITLE
Update schedule.json to enable daily digest in production

### PR DESCRIPTION
**Pull request by phamann**
This enables daily-digests in production! :boom:

### CODE REVIEW

**Comment by phamann** [comment]
This had made me realise that the current model doesn't allow for weekly digests, as the scheduler runs every hour of every day. Should be easy to fix, but something to think about on Monday.

**Comment by keirog** [comment]
Ah yep, hadn't realised that!

The new preference in myft-page uses `digest` as the uuid, but am happy to change that to `email-digest` 👍

**Comment by keirog** [comment]
(https://github.com/Financial-Times/next-myft-page/pull/784)

**Comment by phamann** [comment]
maxresdefault

**Pull request merged**
