### PR TITLE
Update kinesis PartitionKeys

### PR DESCRIPTION
**Pull request by phamann**
I had accidentally left in a test string `nextmyftemail` as the partition key used for the `send-email` kinesis stream. This results in all records being placed on a single shard and thus only one concurrent `send-email` function execution, which is why updating the shard count had no effect on the performance (or time) of sending emails.

This refactors both locations we publish to kinesis to use a truly random (close enough) string generated with `crypto`, this should ensure a much better distribution across the shards and thus higher concurrency.

### CODE REVIEW

**Comment by keirog** [comment]
👍 👍 👍   🚀

**Comment by phamann** [comment]
Have refactored this substantially since last review. Moved the logic into it's own shared lib to be more DRY and added tests.

**Comment by laurieboyes** [comment]
👍

**Comment by keirog** [comment]
^ 😂

**Pull request merged**
