### PR TITLE
Process kinesis records in batches

### PR DESCRIPTION
**Pull request by phamann**
Turns out that processing 100 kinesis Records at a time is hitting the ulimit on the Lambda process and thus casing the function to error. This in turn, is causing the queue to loop infinitely and not process the final records in the queue.

Solution: We still receive 100 records in a batch but the process them in sub-batches of 20 using `directly`. 

google chrome

### CODE REVIEW

**Comment by keirog** [comment]
👍 👍 👍

**Comment by laurieboyes** [comment]
👍  how informed a guess is 20?

**Comment by phamann** [comment]
> how informed a guess is 20?

How long is a piece of string?

**Comment by matthew-andrews** [comment]
Golang has really nice ways of doing this kind of thing.

**Pull request merged**
