### PR TITLE
Premium label

### PR DESCRIPTION
**Pull request by bjfletcher**
Add a premium label to articles that are premium in the digest email.

image

/cc @andygout @phamann

### CODE REVIEW

**Comment by andygout** [comment]
All with just three lines of code!

👍

**Comment by ironsidevsquincy** [comment]
Just an aside, we seem to be doing this test in a few different places - is it worth adding a field to the article when we ingest it into ES?

**Comment by phamann** [comment]
👍 LGTM

**Comment by phamann** [comment]
> is it worth adding a field to the article when we ingest it into ES?

@ironsidevsquincy Yes this was my exact feedback to Ben when he was asking about this work. Surely belongs as an ES transform...

**Comment by andygout** [comment]
Yup, definitely the consensus to do this at source so transform does not need to be repeated.

**Pull request merged**
